apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-telegram-template
  namespace: monitoring
data:
  telegram.tmpl: |
    {{ define "telegram.message" }}
    {{ if eq .Status "firing" }}🫪 *FIRING* 🫪{{ else }}😮‍💨 *RESOLVED* 😮‍💨{{ end }}
    *{{ .CommonLabels.alertname }}*

    {{ range .Alerts }}
    *Summary:* {{ .Annotations.summary }}
    *Description:* {{ .Annotations.description }}
    *Severity:* {{ .Labels.severity }}
    *Starts At:* {{ .StartsAt }}
    {{ if eq $.Status "firing" }}{{ else }}*Ends At:* {{ .EndsAt }}{{ end }}
    {{ if eq $.Status "resolved" }}*Duration:* {{ .EndsAt.Sub .StartsAt }}{{end}}
    {{ end }}
    {{ end }}