apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-telegram-template
  namespace: monitoring
data:
  telegram.tmpl: |
    {{ define "telegram.message" }}
    {{ if eq .Status "firing" }}🫪 *FIRING* 🫪{{ else }}😮‍💨 *RESOLVED* 😮‍💨{{ end }}
    *{{ .CommonLabels.alertname }}*

    {{ range .Alerts }}
    *Summary:* {{ .Annotations.summary }}
    *Description:* {{ .Annotations.description }}
    *Severity:* {{ .Labels.severity }}
    *Duration:* {{ if .StartsAt }}{{ duration .StartsAt }}{{ else }}-{{ end }}
    {{ end }}
    {{ end }}