apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-telegram-bot
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-telegram-bot
  template:
    metadata:
      labels:
        app: alertmanager-telegram-bot
    spec:
      containers:
        - name: bot
          image: metalmatze/alertmanager-bot:0.4.3
          ports:
            - containerPort: 9087
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: alertmanager-telegram
                  key: token
            - name: TELEGRAM_ADMIN
              valueFrom:
                secretKeyRef:
                  name: alertmanager-telegram
                  key: chat_id
            - name: LISTEN_ADDR
              value: "0.0.0.0:9087"
            - name: ALERTMANAGER_URL
              value: "http://monitoring-kube-prometheus-alertmanager:9093"
            - name: STORE
              value: "bolt"
            - name: BOLT_PATH
              value: "/data/bot.db"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
